// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/eqtestcopy/eqtestcopy.proto

package eqtestcopyconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	eqtestcopy "github.com/ikiris/eqtestcopy/proto/eqtestcopy"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EqTestCopyServiceName is the fully-qualified name of the EqTestCopyService service.
	EqTestCopyServiceName = "eqtestcopy.EqTestCopyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EqTestCopyServiceGetCharacterProcedure is the fully-qualified name of the EqTestCopyService's
	// GetCharacter RPC.
	EqTestCopyServiceGetCharacterProcedure = "/eqtestcopy.EqTestCopyService/GetCharacter"
	// EqTestCopyServiceListCharactersProcedure is the fully-qualified name of the EqTestCopyService's
	// ListCharacters RPC.
	EqTestCopyServiceListCharactersProcedure = "/eqtestcopy.EqTestCopyService/ListCharacters"
	// EqTestCopyServiceParseInventoryFileProcedure is the fully-qualified name of the
	// EqTestCopyService's ParseInventoryFile RPC.
	EqTestCopyServiceParseInventoryFileProcedure = "/eqtestcopy.EqTestCopyService/ParseInventoryFile"
	// EqTestCopyServiceUpdateInventoryProcedure is the fully-qualified name of the EqTestCopyService's
	// UpdateInventory RPC.
	EqTestCopyServiceUpdateInventoryProcedure = "/eqtestcopy.EqTestCopyService/UpdateInventory"
	// EqTestCopyServiceGetItemNamesProcedure is the fully-qualified name of the EqTestCopyService's
	// GetItemNames RPC.
	EqTestCopyServiceGetItemNamesProcedure = "/eqtestcopy.EqTestCopyService/GetItemNames"
)

// EqTestCopyServiceClient is a client for the eqtestcopy.EqTestCopyService service.
type EqTestCopyServiceClient interface {
	// Character Management (all require OAuth2 token in metadata)
	GetCharacter(context.Context, *connect.Request[eqtestcopy.GetCharacterRequest]) (*connect.Response[eqtestcopy.CharacterData], error)
	ListCharacters(context.Context, *connect.Request[eqtestcopy.ListCharactersRequest]) (*connect.Response[eqtestcopy.ListCharactersResponse], error)
	ParseInventoryFile(context.Context, *connect.Request[eqtestcopy.ParseInventoryFileRequest]) (*connect.Response[eqtestcopy.ParseInventoryFileResponse], error)
	UpdateInventory(context.Context, *connect.Request[eqtestcopy.UpdateInventoryRequest]) (*connect.Response[eqtestcopy.UpdateInventoryResponse], error)
	GetItemNames(context.Context, *connect.Request[eqtestcopy.GetItemNamesRequest]) (*connect.Response[eqtestcopy.GetItemNamesResponse], error)
}

// NewEqTestCopyServiceClient constructs a client for the eqtestcopy.EqTestCopyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEqTestCopyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EqTestCopyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eqTestCopyServiceMethods := eqtestcopy.File_proto_eqtestcopy_eqtestcopy_proto.Services().ByName("EqTestCopyService").Methods()
	return &eqTestCopyServiceClient{
		getCharacter: connect.NewClient[eqtestcopy.GetCharacterRequest, eqtestcopy.CharacterData](
			httpClient,
			baseURL+EqTestCopyServiceGetCharacterProcedure,
			connect.WithSchema(eqTestCopyServiceMethods.ByName("GetCharacter")),
			connect.WithClientOptions(opts...),
		),
		listCharacters: connect.NewClient[eqtestcopy.ListCharactersRequest, eqtestcopy.ListCharactersResponse](
			httpClient,
			baseURL+EqTestCopyServiceListCharactersProcedure,
			connect.WithSchema(eqTestCopyServiceMethods.ByName("ListCharacters")),
			connect.WithClientOptions(opts...),
		),
		parseInventoryFile: connect.NewClient[eqtestcopy.ParseInventoryFileRequest, eqtestcopy.ParseInventoryFileResponse](
			httpClient,
			baseURL+EqTestCopyServiceParseInventoryFileProcedure,
			connect.WithSchema(eqTestCopyServiceMethods.ByName("ParseInventoryFile")),
			connect.WithClientOptions(opts...),
		),
		updateInventory: connect.NewClient[eqtestcopy.UpdateInventoryRequest, eqtestcopy.UpdateInventoryResponse](
			httpClient,
			baseURL+EqTestCopyServiceUpdateInventoryProcedure,
			connect.WithSchema(eqTestCopyServiceMethods.ByName("UpdateInventory")),
			connect.WithClientOptions(opts...),
		),
		getItemNames: connect.NewClient[eqtestcopy.GetItemNamesRequest, eqtestcopy.GetItemNamesResponse](
			httpClient,
			baseURL+EqTestCopyServiceGetItemNamesProcedure,
			connect.WithSchema(eqTestCopyServiceMethods.ByName("GetItemNames")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eqTestCopyServiceClient implements EqTestCopyServiceClient.
type eqTestCopyServiceClient struct {
	getCharacter       *connect.Client[eqtestcopy.GetCharacterRequest, eqtestcopy.CharacterData]
	listCharacters     *connect.Client[eqtestcopy.ListCharactersRequest, eqtestcopy.ListCharactersResponse]
	parseInventoryFile *connect.Client[eqtestcopy.ParseInventoryFileRequest, eqtestcopy.ParseInventoryFileResponse]
	updateInventory    *connect.Client[eqtestcopy.UpdateInventoryRequest, eqtestcopy.UpdateInventoryResponse]
	getItemNames       *connect.Client[eqtestcopy.GetItemNamesRequest, eqtestcopy.GetItemNamesResponse]
}

// GetCharacter calls eqtestcopy.EqTestCopyService.GetCharacter.
func (c *eqTestCopyServiceClient) GetCharacter(ctx context.Context, req *connect.Request[eqtestcopy.GetCharacterRequest]) (*connect.Response[eqtestcopy.CharacterData], error) {
	return c.getCharacter.CallUnary(ctx, req)
}

// ListCharacters calls eqtestcopy.EqTestCopyService.ListCharacters.
func (c *eqTestCopyServiceClient) ListCharacters(ctx context.Context, req *connect.Request[eqtestcopy.ListCharactersRequest]) (*connect.Response[eqtestcopy.ListCharactersResponse], error) {
	return c.listCharacters.CallUnary(ctx, req)
}

// ParseInventoryFile calls eqtestcopy.EqTestCopyService.ParseInventoryFile.
func (c *eqTestCopyServiceClient) ParseInventoryFile(ctx context.Context, req *connect.Request[eqtestcopy.ParseInventoryFileRequest]) (*connect.Response[eqtestcopy.ParseInventoryFileResponse], error) {
	return c.parseInventoryFile.CallUnary(ctx, req)
}

// UpdateInventory calls eqtestcopy.EqTestCopyService.UpdateInventory.
func (c *eqTestCopyServiceClient) UpdateInventory(ctx context.Context, req *connect.Request[eqtestcopy.UpdateInventoryRequest]) (*connect.Response[eqtestcopy.UpdateInventoryResponse], error) {
	return c.updateInventory.CallUnary(ctx, req)
}

// GetItemNames calls eqtestcopy.EqTestCopyService.GetItemNames.
func (c *eqTestCopyServiceClient) GetItemNames(ctx context.Context, req *connect.Request[eqtestcopy.GetItemNamesRequest]) (*connect.Response[eqtestcopy.GetItemNamesResponse], error) {
	return c.getItemNames.CallUnary(ctx, req)
}

// EqTestCopyServiceHandler is an implementation of the eqtestcopy.EqTestCopyService service.
type EqTestCopyServiceHandler interface {
	// Character Management (all require OAuth2 token in metadata)
	GetCharacter(context.Context, *connect.Request[eqtestcopy.GetCharacterRequest]) (*connect.Response[eqtestcopy.CharacterData], error)
	ListCharacters(context.Context, *connect.Request[eqtestcopy.ListCharactersRequest]) (*connect.Response[eqtestcopy.ListCharactersResponse], error)
	ParseInventoryFile(context.Context, *connect.Request[eqtestcopy.ParseInventoryFileRequest]) (*connect.Response[eqtestcopy.ParseInventoryFileResponse], error)
	UpdateInventory(context.Context, *connect.Request[eqtestcopy.UpdateInventoryRequest]) (*connect.Response[eqtestcopy.UpdateInventoryResponse], error)
	GetItemNames(context.Context, *connect.Request[eqtestcopy.GetItemNamesRequest]) (*connect.Response[eqtestcopy.GetItemNamesResponse], error)
}

// NewEqTestCopyServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEqTestCopyServiceHandler(svc EqTestCopyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eqTestCopyServiceMethods := eqtestcopy.File_proto_eqtestcopy_eqtestcopy_proto.Services().ByName("EqTestCopyService").Methods()
	eqTestCopyServiceGetCharacterHandler := connect.NewUnaryHandler(
		EqTestCopyServiceGetCharacterProcedure,
		svc.GetCharacter,
		connect.WithSchema(eqTestCopyServiceMethods.ByName("GetCharacter")),
		connect.WithHandlerOptions(opts...),
	)
	eqTestCopyServiceListCharactersHandler := connect.NewUnaryHandler(
		EqTestCopyServiceListCharactersProcedure,
		svc.ListCharacters,
		connect.WithSchema(eqTestCopyServiceMethods.ByName("ListCharacters")),
		connect.WithHandlerOptions(opts...),
	)
	eqTestCopyServiceParseInventoryFileHandler := connect.NewUnaryHandler(
		EqTestCopyServiceParseInventoryFileProcedure,
		svc.ParseInventoryFile,
		connect.WithSchema(eqTestCopyServiceMethods.ByName("ParseInventoryFile")),
		connect.WithHandlerOptions(opts...),
	)
	eqTestCopyServiceUpdateInventoryHandler := connect.NewUnaryHandler(
		EqTestCopyServiceUpdateInventoryProcedure,
		svc.UpdateInventory,
		connect.WithSchema(eqTestCopyServiceMethods.ByName("UpdateInventory")),
		connect.WithHandlerOptions(opts...),
	)
	eqTestCopyServiceGetItemNamesHandler := connect.NewUnaryHandler(
		EqTestCopyServiceGetItemNamesProcedure,
		svc.GetItemNames,
		connect.WithSchema(eqTestCopyServiceMethods.ByName("GetItemNames")),
		connect.WithHandlerOptions(opts...),
	)
	return "/eqtestcopy.EqTestCopyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EqTestCopyServiceGetCharacterProcedure:
			eqTestCopyServiceGetCharacterHandler.ServeHTTP(w, r)
		case EqTestCopyServiceListCharactersProcedure:
			eqTestCopyServiceListCharactersHandler.ServeHTTP(w, r)
		case EqTestCopyServiceParseInventoryFileProcedure:
			eqTestCopyServiceParseInventoryFileHandler.ServeHTTP(w, r)
		case EqTestCopyServiceUpdateInventoryProcedure:
			eqTestCopyServiceUpdateInventoryHandler.ServeHTTP(w, r)
		case EqTestCopyServiceGetItemNamesProcedure:
			eqTestCopyServiceGetItemNamesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEqTestCopyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEqTestCopyServiceHandler struct{}

func (UnimplementedEqTestCopyServiceHandler) GetCharacter(context.Context, *connect.Request[eqtestcopy.GetCharacterRequest]) (*connect.Response[eqtestcopy.CharacterData], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eqtestcopy.EqTestCopyService.GetCharacter is not implemented"))
}

func (UnimplementedEqTestCopyServiceHandler) ListCharacters(context.Context, *connect.Request[eqtestcopy.ListCharactersRequest]) (*connect.Response[eqtestcopy.ListCharactersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eqtestcopy.EqTestCopyService.ListCharacters is not implemented"))
}

func (UnimplementedEqTestCopyServiceHandler) ParseInventoryFile(context.Context, *connect.Request[eqtestcopy.ParseInventoryFileRequest]) (*connect.Response[eqtestcopy.ParseInventoryFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eqtestcopy.EqTestCopyService.ParseInventoryFile is not implemented"))
}

func (UnimplementedEqTestCopyServiceHandler) UpdateInventory(context.Context, *connect.Request[eqtestcopy.UpdateInventoryRequest]) (*connect.Response[eqtestcopy.UpdateInventoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eqtestcopy.EqTestCopyService.UpdateInventory is not implemented"))
}

func (UnimplementedEqTestCopyServiceHandler) GetItemNames(context.Context, *connect.Request[eqtestcopy.GetItemNamesRequest]) (*connect.Response[eqtestcopy.GetItemNamesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eqtestcopy.EqTestCopyService.GetItemNames is not implemented"))
}
