---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: eqtestcopy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`eqtestcopy.teraptra.net`)
      kind: Rule
      services:
        - name: eqtestcopy
          port: 3000
          scheme: http