// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proto/eqtestcopy/eqtestcopy.proto

package eqtestcopy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CharacterData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Race          int32                  `protobuf:"varint,3,opt,name=race,proto3" json:"race,omitempty"`
	Class         int32                  `protobuf:"varint,4,opt,name=class,proto3" json:"class,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	ZoneId        int32                  `protobuf:"varint,6,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	X             float32                `protobuf:"fixed32,7,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,8,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,9,opt,name=z,proto3" json:"z,omitempty"`
	Stats         *Stat                  `protobuf:"bytes,10,opt,name=stats,proto3" json:"stats,omitempty"`
	Inventories   []*InventoryItem       `protobuf:"bytes,11,rep,name=inventories,proto3" json:"inventories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterData) Reset() {
	*x = CharacterData{}
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterData) ProtoMessage() {}

func (x *CharacterData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterData.ProtoReflect.Descriptor instead.
func (*CharacterData) Descriptor() ([]byte, []int) {
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CharacterData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterData) GetRace() int32 {
	if x != nil {
		return x.Race
	}
	return 0
}

func (x *CharacterData) GetClass() int32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *CharacterData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CharacterData) GetZoneId() int32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *CharacterData) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CharacterData) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CharacterData) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *CharacterData) GetStats() *Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *CharacterData) GetInventories() []*InventoryItem {
	if x != nil {
		return x.Inventories
	}
	return nil
}

type Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hp            int32                  `protobuf:"varint,1,opt,name=hp,proto3" json:"hp,omitempty"`
	Mana          int32                  `protobuf:"varint,2,opt,name=mana,proto3" json:"mana,omitempty"`
	Str           int32                  `protobuf:"varint,3,opt,name=str,proto3" json:"str,omitempty"`
	Sta           int32                  `protobuf:"varint,4,opt,name=sta,proto3" json:"sta,omitempty"`
	Agi           int32                  `protobuf:"varint,5,opt,name=agi,proto3" json:"agi,omitempty"`
	Dex           int32                  `protobuf:"varint,6,opt,name=dex,proto3" json:"dex,omitempty"`
	Wis           int32                  `protobuf:"varint,7,opt,name=wis,proto3" json:"wis,omitempty"`
	Intel         int32                  `protobuf:"varint,8,opt,name=intel,proto3" json:"intel,omitempty"`
	Cha           int32                  `protobuf:"varint,9,opt,name=cha,proto3" json:"cha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP(), []int{1}
}

func (x *Stat) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Stat) GetMana() int32 {
	if x != nil {
		return x.Mana
	}
	return 0
}

func (x *Stat) GetStr() int32 {
	if x != nil {
		return x.Str
	}
	return 0
}

func (x *Stat) GetSta() int32 {
	if x != nil {
		return x.Sta
	}
	return 0
}

func (x *Stat) GetAgi() int32 {
	if x != nil {
		return x.Agi
	}
	return 0
}

func (x *Stat) GetDex() int32 {
	if x != nil {
		return x.Dex
	}
	return 0
}

func (x *Stat) GetWis() int32 {
	if x != nil {
		return x.Wis
	}
	return 0
}

func (x *Stat) GetIntel() int32 {
	if x != nil {
		return x.Intel
	}
	return 0
}

func (x *Stat) GetCha() int32 {
	if x != nil {
		return x.Cha
	}
	return 0
}

type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int32                  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Charges       int32                  `protobuf:"varint,3,opt,name=charges,proto3" json:"charges,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`                 // Raw location string from TAKP format (e.g., "General1-Slot2")
	SlotName      string                 `protobuf:"bytes,5,opt,name=slot_name,json=slotName,proto3" json:"slot_name,omitempty"` // Friendly slot name for display (e.g., "Head", "General Bag 1 Slot 2")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryItem) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *InventoryItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *InventoryItem) GetCharges() int32 {
	if x != nil {
		return x.Charges
	}
	return 0
}

func (x *InventoryItem) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *InventoryItem) GetSlotName() string {
	if x != nil {
		return x.SlotName
	}
	return ""
}

type GetCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterRequest) Reset() {
	*x = GetCharacterRequest{}
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterRequest) ProtoMessage() {}

func (x *GetCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterRequest) Descriptor() ([]byte, []int) {
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP(), []int{3}
}

func (x *GetCharacterRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type ListCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersRequest) Reset() {
	*x = ListCharactersRequest{}
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersRequest) ProtoMessage() {}

func (x *ListCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersRequest.ProtoReflect.Descriptor instead.
func (*ListCharactersRequest) Descriptor() ([]byte, []int) {
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP(), []int{4}
}

type ListCharactersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*CharacterData       `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersResponse) Reset() {
	*x = ListCharactersResponse{}
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersResponse) ProtoMessage() {}

func (x *ListCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersResponse.ProtoReflect.Descriptor instead.
func (*ListCharactersResponse) Descriptor() ([]byte, []int) {
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP(), []int{5}
}

func (x *ListCharactersResponse) GetCharacters() []*CharacterData {
	if x != nil {
		return x.Characters
	}
	return nil
}

type UpdateInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Inventories   []*InventoryItem       `protobuf:"bytes,2,rep,name=inventories,proto3" json:"inventories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInventoryRequest) Reset() {
	*x = UpdateInventoryRequest{}
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryRequest) ProtoMessage() {}

func (x *UpdateInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateInventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateInventoryRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *UpdateInventoryRequest) GetInventories() []*InventoryItem {
	if x != nil {
		return x.Inventories
	}
	return nil
}

type UpdateInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInventoryResponse) Reset() {
	*x = UpdateInventoryResponse{}
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryResponse) ProtoMessage() {}

func (x *UpdateInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateInventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateInventoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateInventoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetItemNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []int32                `protobuf:"varint,1,rep,packed,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemNamesRequest) Reset() {
	*x = GetItemNamesRequest{}
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemNamesRequest) ProtoMessage() {}

func (x *GetItemNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemNamesRequest.ProtoReflect.Descriptor instead.
func (*GetItemNamesRequest) Descriptor() ([]byte, []int) {
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP(), []int{8}
}

func (x *GetItemNamesRequest) GetItemIds() []int32 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

type GetItemNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemNames     map[int32]string       `protobuf:"bytes,1,rep,name=item_names,json=itemNames,proto3" json:"item_names,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemNamesResponse) Reset() {
	*x = GetItemNamesResponse{}
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemNamesResponse) ProtoMessage() {}

func (x *GetItemNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemNamesResponse.ProtoReflect.Descriptor instead.
func (*GetItemNamesResponse) Descriptor() ([]byte, []int) {
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP(), []int{9}
}

func (x *GetItemNamesResponse) GetItemNames() map[int32]string {
	if x != nil {
		return x.ItemNames
	}
	return nil
}

type ParseInventoryFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   string                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"` // Raw TAKP inventory file content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseInventoryFileRequest) Reset() {
	*x = ParseInventoryFileRequest{}
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseInventoryFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseInventoryFileRequest) ProtoMessage() {}

func (x *ParseInventoryFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseInventoryFileRequest.ProtoReflect.Descriptor instead.
func (*ParseInventoryFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP(), []int{10}
}

func (x *ParseInventoryFileRequest) GetFileContent() string {
	if x != nil {
		return x.FileContent
	}
	return ""
}

type ParseInventoryFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items         []*InventoryItem       `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`                                                                                                     // Parsed items with correct slot IDs
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`                                                                                                   // Parsing errors
	Warnings      []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`                                                                                               // Parsing warnings
	ItemNames     map[int32]string       `protobuf:"bytes,6,rep,name=item_names,json=itemNames,proto3" json:"item_names,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Item names for display
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseInventoryFileResponse) Reset() {
	*x = ParseInventoryFileResponse{}
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseInventoryFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseInventoryFileResponse) ProtoMessage() {}

func (x *ParseInventoryFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eqtestcopy_eqtestcopy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseInventoryFileResponse.ProtoReflect.Descriptor instead.
func (*ParseInventoryFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP(), []int{11}
}

func (x *ParseInventoryFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ParseInventoryFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ParseInventoryFileResponse) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ParseInventoryFileResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ParseInventoryFileResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ParseInventoryFileResponse) GetItemNames() map[int32]string {
	if x != nil {
		return x.ItemNames
	}
	return nil
}

var File_proto_eqtestcopy_eqtestcopy_proto protoreflect.FileDescriptor

const file_proto_eqtestcopy_eqtestcopy_proto_rawDesc = "" +
	"\n" +
	"!proto/eqtestcopy/eqtestcopy.proto\x12\n" +
	"eqtestcopy\"\x9b\x02\n" +
	"\rCharacterData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04race\x18\x03 \x01(\x05R\x04race\x12\x14\n" +
	"\x05class\x18\x04 \x01(\x05R\x05class\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x17\n" +
	"\azone_id\x18\x06 \x01(\x05R\x06zoneId\x12\f\n" +
	"\x01x\x18\a \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\b \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\t \x01(\x02R\x01z\x12&\n" +
	"\x05stats\x18\n" +
	" \x01(\v2\x10.eqtestcopy.StatR\x05stats\x12;\n" +
	"\vinventories\x18\v \x03(\v2\x19.eqtestcopy.InventoryItemR\vinventories\"\xac\x01\n" +
	"\x04Stat\x12\x0e\n" +
	"\x02hp\x18\x01 \x01(\x05R\x02hp\x12\x12\n" +
	"\x04mana\x18\x02 \x01(\x05R\x04mana\x12\x10\n" +
	"\x03str\x18\x03 \x01(\x05R\x03str\x12\x10\n" +
	"\x03sta\x18\x04 \x01(\x05R\x03sta\x12\x10\n" +
	"\x03agi\x18\x05 \x01(\x05R\x03agi\x12\x10\n" +
	"\x03dex\x18\x06 \x01(\x05R\x03dex\x12\x10\n" +
	"\x03wis\x18\a \x01(\x05R\x03wis\x12\x14\n" +
	"\x05intel\x18\b \x01(\x05R\x05intel\x12\x10\n" +
	"\x03cha\x18\t \x01(\x05R\x03cha\"\x94\x01\n" +
	"\rInventoryItem\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x05R\x06slotId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x18\n" +
	"\acharges\x18\x03 \x01(\x05R\acharges\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1b\n" +
	"\tslot_name\x18\x05 \x01(\tR\bslotName\"8\n" +
	"\x13GetCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\"\x17\n" +
	"\x15ListCharactersRequest\"S\n" +
	"\x16ListCharactersResponse\x129\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x19.eqtestcopy.CharacterDataR\n" +
	"characters\"x\n" +
	"\x16UpdateInventoryRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\x12;\n" +
	"\vinventories\x18\x02 \x03(\v2\x19.eqtestcopy.InventoryItemR\vinventories\"M\n" +
	"\x17UpdateInventoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x13GetItemNamesRequest\x12\x19\n" +
	"\bitem_ids\x18\x01 \x03(\x05R\aitemIds\"\xa4\x01\n" +
	"\x14GetItemNamesResponse\x12N\n" +
	"\n" +
	"item_names\x18\x01 \x03(\v2/.eqtestcopy.GetItemNamesResponse.ItemNamesEntryR\titemNames\x1a<\n" +
	"\x0eItemNamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x19ParseInventoryFileRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\tR\vfileContent\"\xc9\x02\n" +
	"\x1aParseInventoryFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x05items\x18\x03 \x03(\v2\x19.eqtestcopy.InventoryItemR\x05items\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\x12T\n" +
	"\n" +
	"item_names\x18\x06 \x03(\v25.eqtestcopy.ParseInventoryFileResponse.ItemNamesEntryR\titemNames\x1a<\n" +
	"\x0eItemNamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xcc\x03\n" +
	"\x11EqTestCopyService\x12J\n" +
	"\fGetCharacter\x12\x1f.eqtestcopy.GetCharacterRequest\x1a\x19.eqtestcopy.CharacterData\x12W\n" +
	"\x0eListCharacters\x12!.eqtestcopy.ListCharactersRequest\x1a\".eqtestcopy.ListCharactersResponse\x12c\n" +
	"\x12ParseInventoryFile\x12%.eqtestcopy.ParseInventoryFileRequest\x1a&.eqtestcopy.ParseInventoryFileResponse\x12Z\n" +
	"\x0fUpdateInventory\x12\".eqtestcopy.UpdateInventoryRequest\x1a#.eqtestcopy.UpdateInventoryResponse\x12Q\n" +
	"\fGetItemNames\x12\x1f.eqtestcopy.GetItemNamesRequest\x1a .eqtestcopy.GetItemNamesResponseB/Z-github.com/ikiris/eqtestcopy/proto/eqtestcopyb\x06proto3"

var (
	file_proto_eqtestcopy_eqtestcopy_proto_rawDescOnce sync.Once
	file_proto_eqtestcopy_eqtestcopy_proto_rawDescData []byte
)

func file_proto_eqtestcopy_eqtestcopy_proto_rawDescGZIP() []byte {
	file_proto_eqtestcopy_eqtestcopy_proto_rawDescOnce.Do(func() {
		file_proto_eqtestcopy_eqtestcopy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_eqtestcopy_eqtestcopy_proto_rawDesc), len(file_proto_eqtestcopy_eqtestcopy_proto_rawDesc)))
	})
	return file_proto_eqtestcopy_eqtestcopy_proto_rawDescData
}

var file_proto_eqtestcopy_eqtestcopy_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_eqtestcopy_eqtestcopy_proto_goTypes = []any{
	(*CharacterData)(nil),              // 0: eqtestcopy.CharacterData
	(*Stat)(nil),                       // 1: eqtestcopy.Stat
	(*InventoryItem)(nil),              // 2: eqtestcopy.InventoryItem
	(*GetCharacterRequest)(nil),        // 3: eqtestcopy.GetCharacterRequest
	(*ListCharactersRequest)(nil),      // 4: eqtestcopy.ListCharactersRequest
	(*ListCharactersResponse)(nil),     // 5: eqtestcopy.ListCharactersResponse
	(*UpdateInventoryRequest)(nil),     // 6: eqtestcopy.UpdateInventoryRequest
	(*UpdateInventoryResponse)(nil),    // 7: eqtestcopy.UpdateInventoryResponse
	(*GetItemNamesRequest)(nil),        // 8: eqtestcopy.GetItemNamesRequest
	(*GetItemNamesResponse)(nil),       // 9: eqtestcopy.GetItemNamesResponse
	(*ParseInventoryFileRequest)(nil),  // 10: eqtestcopy.ParseInventoryFileRequest
	(*ParseInventoryFileResponse)(nil), // 11: eqtestcopy.ParseInventoryFileResponse
	nil,                                // 12: eqtestcopy.GetItemNamesResponse.ItemNamesEntry
	nil,                                // 13: eqtestcopy.ParseInventoryFileResponse.ItemNamesEntry
}
var file_proto_eqtestcopy_eqtestcopy_proto_depIdxs = []int32{
	1,  // 0: eqtestcopy.CharacterData.stats:type_name -> eqtestcopy.Stat
	2,  // 1: eqtestcopy.CharacterData.inventories:type_name -> eqtestcopy.InventoryItem
	0,  // 2: eqtestcopy.ListCharactersResponse.characters:type_name -> eqtestcopy.CharacterData
	2,  // 3: eqtestcopy.UpdateInventoryRequest.inventories:type_name -> eqtestcopy.InventoryItem
	12, // 4: eqtestcopy.GetItemNamesResponse.item_names:type_name -> eqtestcopy.GetItemNamesResponse.ItemNamesEntry
	2,  // 5: eqtestcopy.ParseInventoryFileResponse.items:type_name -> eqtestcopy.InventoryItem
	13, // 6: eqtestcopy.ParseInventoryFileResponse.item_names:type_name -> eqtestcopy.ParseInventoryFileResponse.ItemNamesEntry
	3,  // 7: eqtestcopy.EqTestCopyService.GetCharacter:input_type -> eqtestcopy.GetCharacterRequest
	4,  // 8: eqtestcopy.EqTestCopyService.ListCharacters:input_type -> eqtestcopy.ListCharactersRequest
	10, // 9: eqtestcopy.EqTestCopyService.ParseInventoryFile:input_type -> eqtestcopy.ParseInventoryFileRequest
	6,  // 10: eqtestcopy.EqTestCopyService.UpdateInventory:input_type -> eqtestcopy.UpdateInventoryRequest
	8,  // 11: eqtestcopy.EqTestCopyService.GetItemNames:input_type -> eqtestcopy.GetItemNamesRequest
	0,  // 12: eqtestcopy.EqTestCopyService.GetCharacter:output_type -> eqtestcopy.CharacterData
	5,  // 13: eqtestcopy.EqTestCopyService.ListCharacters:output_type -> eqtestcopy.ListCharactersResponse
	11, // 14: eqtestcopy.EqTestCopyService.ParseInventoryFile:output_type -> eqtestcopy.ParseInventoryFileResponse
	7,  // 15: eqtestcopy.EqTestCopyService.UpdateInventory:output_type -> eqtestcopy.UpdateInventoryResponse
	9,  // 16: eqtestcopy.EqTestCopyService.GetItemNames:output_type -> eqtestcopy.GetItemNamesResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_eqtestcopy_eqtestcopy_proto_init() }
func file_proto_eqtestcopy_eqtestcopy_proto_init() {
	if File_proto_eqtestcopy_eqtestcopy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_eqtestcopy_eqtestcopy_proto_rawDesc), len(file_proto_eqtestcopy_eqtestcopy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_eqtestcopy_eqtestcopy_proto_goTypes,
		DependencyIndexes: file_proto_eqtestcopy_eqtestcopy_proto_depIdxs,
		MessageInfos:      file_proto_eqtestcopy_eqtestcopy_proto_msgTypes,
	}.Build()
	File_proto_eqtestcopy_eqtestcopy_proto = out.File
	file_proto_eqtestcopy_eqtestcopy_proto_goTypes = nil
	file_proto_eqtestcopy_eqtestcopy_proto_depIdxs = nil
}
