// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/eqtestcopy/eqtestcopy.proto

package eqtestcopy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EqTestCopyService_GetCharacter_FullMethodName       = "/eqtestcopy.EqTestCopyService/GetCharacter"
	EqTestCopyService_ListCharacters_FullMethodName     = "/eqtestcopy.EqTestCopyService/ListCharacters"
	EqTestCopyService_ParseInventoryFile_FullMethodName = "/eqtestcopy.EqTestCopyService/ParseInventoryFile"
	EqTestCopyService_UpdateInventory_FullMethodName    = "/eqtestcopy.EqTestCopyService/UpdateInventory"
	EqTestCopyService_GetItemNames_FullMethodName       = "/eqtestcopy.EqTestCopyService/GetItemNames"
)

// EqTestCopyServiceClient is the client API for EqTestCopyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EqTestCopyServiceClient interface {
	// Character Management (all require OAuth2 token in metadata)
	GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*CharacterData, error)
	ListCharacters(ctx context.Context, in *ListCharactersRequest, opts ...grpc.CallOption) (*ListCharactersResponse, error)
	ParseInventoryFile(ctx context.Context, in *ParseInventoryFileRequest, opts ...grpc.CallOption) (*ParseInventoryFileResponse, error)
	UpdateInventory(ctx context.Context, in *UpdateInventoryRequest, opts ...grpc.CallOption) (*UpdateInventoryResponse, error)
	GetItemNames(ctx context.Context, in *GetItemNamesRequest, opts ...grpc.CallOption) (*GetItemNamesResponse, error)
}

type eqTestCopyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEqTestCopyServiceClient(cc grpc.ClientConnInterface) EqTestCopyServiceClient {
	return &eqTestCopyServiceClient{cc}
}

func (c *eqTestCopyServiceClient) GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*CharacterData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CharacterData)
	err := c.cc.Invoke(ctx, EqTestCopyService_GetCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eqTestCopyServiceClient) ListCharacters(ctx context.Context, in *ListCharactersRequest, opts ...grpc.CallOption) (*ListCharactersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCharactersResponse)
	err := c.cc.Invoke(ctx, EqTestCopyService_ListCharacters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eqTestCopyServiceClient) ParseInventoryFile(ctx context.Context, in *ParseInventoryFileRequest, opts ...grpc.CallOption) (*ParseInventoryFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseInventoryFileResponse)
	err := c.cc.Invoke(ctx, EqTestCopyService_ParseInventoryFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eqTestCopyServiceClient) UpdateInventory(ctx context.Context, in *UpdateInventoryRequest, opts ...grpc.CallOption) (*UpdateInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInventoryResponse)
	err := c.cc.Invoke(ctx, EqTestCopyService_UpdateInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eqTestCopyServiceClient) GetItemNames(ctx context.Context, in *GetItemNamesRequest, opts ...grpc.CallOption) (*GetItemNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemNamesResponse)
	err := c.cc.Invoke(ctx, EqTestCopyService_GetItemNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EqTestCopyServiceServer is the server API for EqTestCopyService service.
// All implementations must embed UnimplementedEqTestCopyServiceServer
// for forward compatibility.
type EqTestCopyServiceServer interface {
	// Character Management (all require OAuth2 token in metadata)
	GetCharacter(context.Context, *GetCharacterRequest) (*CharacterData, error)
	ListCharacters(context.Context, *ListCharactersRequest) (*ListCharactersResponse, error)
	ParseInventoryFile(context.Context, *ParseInventoryFileRequest) (*ParseInventoryFileResponse, error)
	UpdateInventory(context.Context, *UpdateInventoryRequest) (*UpdateInventoryResponse, error)
	GetItemNames(context.Context, *GetItemNamesRequest) (*GetItemNamesResponse, error)
	mustEmbedUnimplementedEqTestCopyServiceServer()
}

// UnimplementedEqTestCopyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEqTestCopyServiceServer struct{}

func (UnimplementedEqTestCopyServiceServer) GetCharacter(context.Context, *GetCharacterRequest) (*CharacterData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCharacter not implemented")
}
func (UnimplementedEqTestCopyServiceServer) ListCharacters(context.Context, *ListCharactersRequest) (*ListCharactersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCharacters not implemented")
}
func (UnimplementedEqTestCopyServiceServer) ParseInventoryFile(context.Context, *ParseInventoryFileRequest) (*ParseInventoryFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseInventoryFile not implemented")
}
func (UnimplementedEqTestCopyServiceServer) UpdateInventory(context.Context, *UpdateInventoryRequest) (*UpdateInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInventory not implemented")
}
func (UnimplementedEqTestCopyServiceServer) GetItemNames(context.Context, *GetItemNamesRequest) (*GetItemNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemNames not implemented")
}
func (UnimplementedEqTestCopyServiceServer) mustEmbedUnimplementedEqTestCopyServiceServer() {}
func (UnimplementedEqTestCopyServiceServer) testEmbeddedByValue()                           {}

// UnsafeEqTestCopyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EqTestCopyServiceServer will
// result in compilation errors.
type UnsafeEqTestCopyServiceServer interface {
	mustEmbedUnimplementedEqTestCopyServiceServer()
}

func RegisterEqTestCopyServiceServer(s grpc.ServiceRegistrar, srv EqTestCopyServiceServer) {
	// If the following call pancis, it indicates UnimplementedEqTestCopyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EqTestCopyService_ServiceDesc, srv)
}

func _EqTestCopyService_GetCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EqTestCopyServiceServer).GetCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EqTestCopyService_GetCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EqTestCopyServiceServer).GetCharacter(ctx, req.(*GetCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EqTestCopyService_ListCharacters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCharactersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EqTestCopyServiceServer).ListCharacters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EqTestCopyService_ListCharacters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EqTestCopyServiceServer).ListCharacters(ctx, req.(*ListCharactersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EqTestCopyService_ParseInventoryFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseInventoryFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EqTestCopyServiceServer).ParseInventoryFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EqTestCopyService_ParseInventoryFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EqTestCopyServiceServer).ParseInventoryFile(ctx, req.(*ParseInventoryFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EqTestCopyService_UpdateInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EqTestCopyServiceServer).UpdateInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EqTestCopyService_UpdateInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EqTestCopyServiceServer).UpdateInventory(ctx, req.(*UpdateInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EqTestCopyService_GetItemNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EqTestCopyServiceServer).GetItemNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EqTestCopyService_GetItemNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EqTestCopyServiceServer).GetItemNames(ctx, req.(*GetItemNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EqTestCopyService_ServiceDesc is the grpc.ServiceDesc for EqTestCopyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EqTestCopyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eqtestcopy.EqTestCopyService",
	HandlerType: (*EqTestCopyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCharacter",
			Handler:    _EqTestCopyService_GetCharacter_Handler,
		},
		{
			MethodName: "ListCharacters",
			Handler:    _EqTestCopyService_ListCharacters_Handler,
		},
		{
			MethodName: "ParseInventoryFile",
			Handler:    _EqTestCopyService_ParseInventoryFile_Handler,
		},
		{
			MethodName: "UpdateInventory",
			Handler:    _EqTestCopyService_UpdateInventory_Handler,
		},
		{
			MethodName: "GetItemNames",
			Handler:    _EqTestCopyService_GetItemNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/eqtestcopy/eqtestcopy.proto",
}
